import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "@/components/Heading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Radio Imaging Showreel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Heading />
        {children}
      </body>
    </html>
  );
}
